Repository cuttle-cards/cuttle, pull requests merged in 2022-11, with the labels that each got.

#200 Replace halloween logo with original logo
  client/js/img/logo.png
Labels: hacktoberfest-accepted

#234 Fix/scuttle animation firefox
  client/js/components/GameView/Card.vue
  package.json
Labels: bug

#242 Feat/update deps
  .nvmrc
  package-lock.json
  package.json
Labels: dev experience
