Repository cuttle-cards/cuttle, pull requests merged in 2022-10, with the labels that each got.

#100 Feat/automated rankings
  api/controllers/game/concede.js
  api/controllers/game/create.js
  api/controllers/game/pass.js
  api/controllers/game/ready.js
  api/controllers/game/stalemate.js
  api/helpers/add-game-to-match.js
  api/helpers/find-or-create-current-match.js
  api/hooks/customGameHook/index.js
  api/models/Game.js
  api/models/Match.js
  api/services/gameService.js
  client/js/components/CreateGameDialog.vue
  client/js/components/GameListItem.vue
  client/js/store/modules/gameList.js
  client/js/views/Home.vue
  config/env/development.js
  package.json
  tests/e2e/specs/in-game/gameOver.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
Labels: requires migration

#125 [Feature]: Increase GitHub Action Timeout
  .github/workflows/pr-actions.yml
Labels: enhancement

#123 [Feature]: Track my preference for ranked vs unranked games, resolves…
  client/js/components/CreateGameDialog.vue
  tests/e2e/specs/out-of-game/home.spec.js
Labels: enhancement

#122 [Feature]: Lobby should show whether a game is ranked, resolves #106
  client/js/store/modules/game.js
  client/js/views/Lobby.vue
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: enhancement

#124 [Bug]: User session is invalid when logging in consecutively, resolves #116
  api/controllers/UserController.js
  client/js/plugins/sails.js
  client/js/store/modules/auth.js
  client/js/views/LoginSignup.vue
  package.json
Labels: bug

#153 Reduce noise from npm output
  .npmrc
Labels: enhancement, hacktoberfest-accepted

#161 Add API status endpoint
  api/controllers/HealthController.js
  api/helpers/get-api-health.js
  config/routes.js
  package-lock.json
  tests/e2e/specs/out-of-game/health.spec.js
Labels: enhancement, hacktoberfest-accepted

#198 Display players lost to in Stats Leaderboard
  client/js/components/StatsLeaderboard.vue
  client/js/components/StatsLeaderboardCell.vue
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: hacktoberfest-accepted

#204 feature/game-rules-md - #178 separated game rules from README.md
  README.md
  docs/GAME_RULES.md
Labels: hacktoberfest-accepted, dev experience

#203 Feature/adds win rate on player menu stats
  client/js/components/StatsLeaderboard.vue
  client/js/components/StatsLeaderboardCell.vue
  package.json
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: hacktoberfest-accepted
