Repository cuttle-cards/cuttle, pull requests merged in 2023-03, with the labels that each got.

#342 [Feature]: Revise scoring system to 5, 4, 3, 2, 1 for each week
  package.json
  src/components/StatsLeaderboard.vue
  src/components/StatsLeaderboardCell.vue
  src/components/StatsScoringDialog.vue
  tests/e2e/fixtures/statsFixtures.js
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: enhancement, minor-version

#352 added v-if to game-over-dialog component
  package-lock.json
  package.json
  src/components/GameView/GameDialogs.vue
Labels: patch-version

#356 Bug#355
  package-lock.json
  package.json
  src/components/AwardCard.vue
  src/components/StatsScoringDialog.vue
Labels: bug, patch-version

#339 Feat/Game over rework - resolves #105
  api/controllers/game/concede.js
  api/controllers/game/pass.js
  api/controllers/game/stalemate.js
  api/helpers/add-game-to-match.js
  api/services/gameService.js
  package.json
  src/components/GameView/GameDialogs.vue
  src/components/GameView/GameOverDialog.vue
  src/store/modules/game.js
  tests/e2e/specs/in-game/gameOver.spec.js
Labels: enhancement, minor-version

#341 Game overlays heading mobile #328
  package-lock.json
  package.json
  src/App.vue
  src/components/GameView/GameOverlays.vue
  src/sass/variables.scss
  src/views/StatsView.vue
  vite.config.js
Labels: patch-version

#345 Feature/spectate games
  api/controllers/TestController.js
  api/controllers/UserController.js
  api/controllers/game/concede.js
  api/controllers/game/game-over.js
  api/controllers/game/get-list.js
  api/controllers/game/ready.js
  api/controllers/game/spectate.js
  api/helpers/ find-spectatable-games.js
  api/policies/isInGame.js
  api/services/gameService.js
  config/policies.js
  config/routes.js
  package.json
  src/components/GameListItem.vue
  src/components/GameView/GameOverDialog.vue
  src/components/GameView/GameOverlays.vue
  src/plugins/sails.js
  src/router.js
  src/store/modules/game.js
  src/store/modules/gameList.js
  src/views/GameView.vue
  src/views/HomeView.vue
  tests/e2e/specs/in-game/gameOver.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
Labels: minor-version
