Repository cuttle-cards/cuttle, pull requests merged in 2023-11, with the labels that each got.

#733 feat: set spooky logo for the month of october
  src/composables/themedLogo.js
Labels: version-minor, frontend

#738 Feat #627 Counter Dialog Localization
  src/routes/game/components/CannotCounterDialog.vue
  src/routes/game/components/ChooseTwoDialog.vue
  src/routes/game/components/ChooseWhetherToCounterDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/one-offs/0_countering.spec.js
  tests/e2e/specs/in-game/reconnecting.spec.js
Labels: frontend

#740 Feat/translate game overlays
  src/routes/game/components/GameOverlays.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: version-minor, frontend

#746 Remastered french translation
  src/translations/fr.json
Labels: internationalization

#741 updates GameOverDialog to contain ES and FR localizations #631
  src/routes/game/components/GameOverDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: internationalization

#754 fix: replace Math.min() with Math.max() to prevent player count from …
  src/stores/gameList.js
Labels: bug, version-patch

#756 put info button to the left of switch and fixed alignment
  src/components/StatsScoringDialog.vue
  src/routes/home/components/CreateGameDialog.vue
Labels: frontend

#766 added line 84 to CONTRIBUTING.MD
  docs/CONTRIBUTING.md
Labels: documentation

#771 localization in GameUnavailableOverlay
  src/routes/game/components/GameUnavailableOverlay.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: frontend, internationalization

#770 style: revise counter and resolve buttons
  src/routes/game/components/CannotCounterDialog.vue
  src/routes/game/components/ChooseWhetherToCounterDialog.vue
Labels: enhancement, version-patch, frontend

#719 Bug/707 LobbyView is not playing a sound when players join
  src/routes/lobby/LobbyView.vue
Labels: hacktoberfest, frontend

#787 feat: change lobby sound to bubbles3.mp3
  public/sounds/lobby/enter-lobby.mp3
Labels: enhancement, version-patch, frontend

#800 style(GameOverDialog): change button color to surface-2
  src/routes/game/components/GameOverDialog.vue
Labels: version-patch, frontend

#799 fix(RulesView): replace mid-crown icon with mdi-crown
  src/routes/rules/RulesView.vue
Labels: bug, version-patch

#801 chore: remove unused config/locales folder
  config/locales/_README.md
  config/locales/de.json
  config/locales/en.json
  config/locales/es.json
  config/locales/fr.json
Labels: dev experience, version-patch

#783 Fix/application locking
  api/controllers/game/ready.js
  api/helpers/lock-game.js
  api/helpers/unlock-game.js
  api/models/Game.js
  config/policies.js
Labels: bug, version-minor

#802 es.json better translation
  src/translations/es.json
Labels: internationalization

#796 Feat #491 Refactor stats
  api/controllers/StatsController.js
  api/helpers/get-seasons-without-rankings.js
  api/policies/hasSeasonId.js
  config/policies.js
  config/routes.js
  src/routes/stats/StatsView.vue
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: backend, frontend

#701 DevEx #621 updateGame() Refactor
  src/routes/game/GameView.vue
  src/stores/game.js
Labels: dev experience, version-patch

#812 DevEx: Whole lotta package updates, November 2023 edition
  package-lock.json
  package.json
  src/components/MarkdownContent.vue
  src/components/TheHeader.vue
  src/components/TheLanguageSelector.vue
  src/plugins/vuetify.js
  src/routes/stats/components/StatsLeaderboardCell.vue
Labels: version-minor

#816 Update CODEOWNERS
  .github/CODEOWNERS
Labels: version-patch

#815 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, version-patch

#819 Fix French translations
  src/translations/fr.json
Labels: version-patch, frontend, internationalization
