Repository cuttle-cards/cuttle, pull requests merged in 2023-10, with the labels that each got.

#606 Try running version bump with branch protection
  .github/workflows/bump-version.yml
  package-lock.json
  package.json
  src/components/LobbyPlayerIndicator.vue
  src/components/TheFooter.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/views/LobbyView.vue
  tests/e2e/specs/out-of-game/localization.spec.js
Labels: version-patch

#608 Apply PAT to enable pushing to protected branch
  .github/workflows/bump-version.yml
Labels: version-minor

#612 feat: add username to origin config
  .github/workflows/bump-version.yml
Labels: version-minor

#641 Autopush to main-temporary-2 without token
  .github/workflows/bump-version.yml
Labels: version-patch

#642 Feat/automate version bump
  .github/workflows/bump-version.yml
Labels: version-patch

#643 set version bump to run on main-temporary
  .github/workflows/bump-version.yml
Labels: version-minor

#644 Rerun version bump
  .github/workflows/bump-version.yml
Labels: version-minor

#650 trying again w/ reduced scope
  .github/workflows/bump-version.yml
Labels: version-minor

#617 [DevEx]: components name instance in pascalcase
  .eslintrc.js
  src/App.vue
  src/components/CreateGameDialog.vue
  src/components/GameView/CannotCounterDialog.vue
  src/components/GameView/CardListSortable.vue
  src/components/GameView/ChooseTwoDialog.vue
  src/components/GameView/ChooseWhetherToCounterDialog.vue
  src/components/GameView/CounterDialog.vue
  src/components/GameView/FourDialog.vue
  src/components/GameView/GameCard.vue
  src/components/GameView/GameDialogs.vue
  src/components/GameView/GameMenu.vue
  src/components/GameView/GameOverDialog.vue
  src/components/GameView/GameOverlays.vue
  src/components/GameView/GameUnavailableView.vue
  src/components/GameView/MoveChoiceOverlay.vue
  src/components/GameView/OpponentRequestedStalemateDialog.vue
  src/components/GameView/ReauthenticateDialog.vue
  src/components/GameView/ScrapDialog.vue
  src/components/GameView/SevenDoubleJacksDialog.vue
  src/components/GameView/TargetSelectionOverlay.vue
  src/components/GameView/ThreeDialog.vue
  src/components/HowItWorksDialog.vue
  src/components/RulesDialog.vue
  src/components/StatsLeaderboard.vue
  src/components/StatsScoringDialog.vue
  src/components/StatsUsageChart.vue
  src/views/GameView.vue
  src/views/HomeView.vue
  src/views/LobbyView.vue
  src/views/LoginView.vue
  src/views/RulesView.vue
  src/views/StatsView.vue
Labels: version-patch

#647 575: Fix warnings
  src/components/GameView/ReauthenticateDialog.vue
  src/components/GameView/ScrapDialog.vue
Labels: version-patch

#656 Feat/spooky logo
  public/img/logo-spooky.png
  src/composables/themedLogo.js
  src/views/LobbyView.vue
  src/views/LoginView.vue
  src/views/RulesView.vue
Labels: hacktoberfest, version-minor, frontend

#659 Update node to 18.18
  .github/workflows/run-npm-script.yml
  .nvmrc
  docker/Dockerfile
  package-lock.json
  package.json
Labels: hacktoberfest, version-minor

#663 Feature/storybook 7
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/storybook.css
  package-lock.json
  package.json
  src/components/AwardCard.vue
  stories/components/AwardCard.stories.js
  stories/components/GameView/UsernameToolTip.stories.js
Labels: enhancement, hacktoberfest, dev experience, version-minor

#661 Upgrade Cypress to version 13, resolves #660
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest, dev experience, version-minor

#654 Feat/622 Enable language selection before login
  src/components/TheLanguageSelector.vue
  src/components/TheUserMenu.vue
  src/views/LoginView.vue
Labels: hacktoberfest, frontend

#665 Feat/ 637 Enable selecting your preferred language from the `GameMenu`
  src/components/GameView/GameMenu.vue
Labels: hacktoberfest, frontend

#603 How it works dialog translation
  src/components/HowItWorksDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#670 feat: cancel icon alignment updated in scrap list
  src/routes/game/components/CardListSortable.vue
Labels: hacktoberfest, frontend

#658 Added eslint curly error config and fixed errors
  .eslintrc.js
  api/controllers/game/face-card.js
  api/controllers/game/jack.js
  api/controllers/game/points.js
  api/controllers/game/resolve.js
  api/controllers/game/seven/face-card.js
  api/controllers/game/seven/jack.js
  api/controllers/game/seven/points.js
  api/controllers/game/seven/targeted-one-off.js
  api/controllers/game/seven/untargeted-one-off.js
  api/controllers/game/targeted-one-off.js
  api/controllers/game/untargeted-one-off.js
  api/helpers/add-game-to-match.js
  api/policies/hasCardIdOne.js
  api/policies/hasCardIdOneAndTwo.js
  api/policies/hasGameId.js
  api/policies/hasOpId.js
  api/policies/hasTargetId.js
  api/policies/hasTargetType.js
  src/routes/game/GameView.vue
  src/routes/game/components/MoveChoiceOverlay.vue
  src/routes/game/components/SevenDoubleJacksDialog.vue
  src/routes/home/HomeView.vue
  src/routes/stats/components/StatsLeaderboard.vue
  src/stores/game.js
  tests/e2e/support/helpers.js
Labels: hacktoberfest, dev experience

#676 feat: applied translation to scrap dialog
  src/routes/game/components/CardListSortable.vue
  src/routes/game/components/ScrapDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#677 Feat/628 Apply translations/localization to all the text in the FourDialog
  src/routes/game/components/FourDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#653 Feat #618 animate threes
  api/controllers/game/resolve-three.js
  src/plugins/sockets/inGameEvents.js
  src/routes/game/GameView.vue
  src/routes/game/components/GameCard.vue
  src/stores/game.js
  tests/e2e/specs/in-game/one-offs/3_threes.spec.js
Labels: hacktoberfest, backend, frontend

#640 Feature/issue-638
  src/routes/game/components/SpectatorListMenu.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#684 [Feat #636] Add localization to GameMenu
  src/routes/game/components/GameMenu.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#686 Feat #619 Animate fours
  api/controllers/game/resolve-four.js
  api/services/gameService.js
  src/plugins/sockets/inGameEvents.js
  src/routes/game/GameView.vue
  src/routes/game/components/GameCard.vue
  src/stores/game.js
Labels: hacktoberfest, backend, frontend

#700 feat(bump-version.yml): skip checkout if push token is missing
  .github/workflows/bump-version.yml
Labels: hacktoberfest, dev experience, version-minor

#685 (#553) Add translations to the RulesView
  src/routes/rules/RulesView.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#692 DevEx/690 Refactor <v-list> inside `ScoreGoalToolTip`
  src/routes/game/components/ScoreGoalToolTip.vue
Labels: hacktoberfest, dev experience

#703 Added translations to OpponentRequesteStalemateDialog
  src/routes/game/components/OpponentRequestedStalemateDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest

#708 Game icons
  src/routes/home/components/GameListItem.vue
  src/routes/lobby/LobbyView.vue
Labels: hacktoberfest, frontend

#716 fix: no-op configure git step of bump-version action when token is mi…
  .github/workflows/bump-version.yml
Labels: hacktoberfest, dev experience, version-patch

#714 fix: update test references to ranked icon to use sword-cross
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: hacktoberfest, dev experience, version-patch

#717 Bug #471 setupGameAsP0 403
  tests/e2e/specs/in-game/one-offs/1_aces.spec.js
  tests/e2e/specs/in-game/one-offs/6_sixes.spec.js
  tests/e2e/support/commands.js
Labels: bug, dev experience

#680 working on three dialog translation
  src/routes/game/components/ThreeDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#687 Feature/issue 625
  src/routes/game/GameView.vue
  src/routes/game/components/MoveChoiceOverlay.vue
  src/routes/game/components/ScoreGoalToolTip.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: hacktoberfest, frontend

#721 fix: mode change type error
  api/controllers/game/set-is-ranked.js
Labels: bug, hacktoberfest

#724 Add player joined lobby animation
  public/img/waves.svg
  src/routes/lobby/components/LobbyPlayerIndicator.vue
Labels: hacktoberfest, frontend

#726 Update Cypress V13.4.0
  package-lock.json
  package.json
Labels: hacktoberfest, dev experience

#730 Feature #723 - Animate when players leaves the lobby
  src/routes/lobby/LobbyView.vue
  src/routes/lobby/components/LobbyPlayerIndicator.vue
Labels: hacktoberfest, frontend
