Repository cuttle-cards/cuttle, pull requests merged in 2023-02, with the labels that each got.

#319 Feat/various adjustments
  src/components/GameView/GameOverDialog.vue
Labels: bug

#321 Convert snackbar to base component
  src/components/GameView/ReauthenticateDialog.vue
  src/components/Global/BaseSnackbar.vue
  src/views/GameView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
Labels: bug, enhancement

#325 Fix/sort leaderboard by rank
  package.json
  src/components/StatsLeaderboard.vue
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: bug, patch-version

#326 Style/history margin
  package.json
  src/views/GameView.vue
Labels: patch-version

#329 Style/create game switch color
  package.json
  src/components/CreateGameDialog.vue
Labels: patch-version

#331 Reset state at initialize for each game - resolves #318
  package.json
  src/components/GameView/GameOverlays.vue
  src/plugins/sails.js
  src/store/modules/game.js
  tests/e2e/specs/in-game/gameOver.spec.js
Labels: patch-version

#330 Feat/devtools -- resolves #316
  .env
  .eslintrc.js
  .github/workflows/pr-actions.yml
  cypress.config.js
  docs/setup-development.md
  package-lock.json
  package.json
  src/main.js
  tests/e2e/specs/global/tools.spec.prod.js
  tests/unit/utils/config-utils.spec.js
  utils/config-utils.js
Labels: dev experience
