Repository cuttle-cards/cuttle, pull requests merged in 2023-01, with the labels that each got.

#277 [DevEx]: Enable Vuetify eslint errors and fix them across the app, fixes #275
  .eslintrc.js
  .vscode/tasks.json
  src/components/CreateGameDialog.vue
  src/components/GameListItem.vue
  src/components/GameView/CannotCounterDialog.vue
  src/components/GameView/CardListSortable.vue
  src/components/GameView/CounterDialog.vue
  src/components/GameView/FourDialog.vue
  src/components/GameView/GameCard.vue
  src/components/GameView/GameMenu.vue
  src/components/GameView/GameOverDialog.vue
  src/components/GameView/GameOverlays.vue
  src/components/GameView/MoveChoiceCard.vue
  src/components/GameView/MoveChoiceOverlay.vue
  src/components/GameView/OpponentRequestedStalemateDialog.vue
  src/components/GameView/ReauthenticateDialog.vue
  src/components/GameView/ScoreGoalToolTip.vue
  src/components/GameView/ScrapDialog.vue
  src/components/GameView/SevenDoubleJacksDialog.vue
  src/components/GameView/TargetSelectionOverlay.vue
  src/components/NavigationDrawer.vue
  src/components/RulesDialog.vue
  src/components/StatsLeaderboard.vue
  src/components/StatsLeaderboardCell.vue
  src/components/StatsScoringDialog.vue
  src/router.js
  src/views/About.vue
  src/views/GameView.vue
  src/views/HomeView.vue
  src/views/LobbyView.vue
  src/views/LoginView.vue
  src/views/RulesView.vue
  src/views/StatsView.vue
Labels: dev experience

#279 Fix /health check and turn on tests, closes #267
  tests/e2e/specs/out-of-game/health.spec.js
  vite.config.js
  vue.config.js
Labels: bug

#280 feat: hide the stats leaderboard when no matches are available
  client/js/components/StatsLeaderboard.vue
  client/js/views/Stats.vue
  tests/e2e/fixtures/statsFixtures.js
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: enhancement

#292 Feat: Fix home spec tests, resolves #268
  src/components/AwardCard.vue
  src/components/CreateGameDialog.vue
  src/components/StatsScoringDialog.vue
  tests/e2e/specs/out-of-game/home.spec.js
Labels: dev experience

#296 [DevEx]: Fix failing lobby.spec test, fixes #269
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: dev experience

#294 [DevEx]: Fix failing navigation.spec test, fixes #270
  tests/e2e/specs/out-of-game/navigation.spec.js
Labels: dev experience

#295 [DevEx]: Fix failing layout.spec test, fixes #263
  tests/e2e/specs/in-game/layout.spec.js
Labels: dev experience

#297 feat: add codeowners file
  .github/CODEOWNERS
Labels: dev experience

#299 chore: merge 3.4.2 in to feature/vue-3
  src/router.js
  src/views/LoginView.vue
  tests/e2e/specs/out-of-game/authentication.spec.js
Labels: dev experience
