Repository cuttle-cards/cuttle, pull requests merged in 2023-04, with the labels that each got.

#382 Feat/show one offs in overlay
  package.json
  src/components/GameView/GameCard.vue
  src/components/GameView/GameOverlays.vue
  tests/e2e/specs/in-game/countering.spec.js
Labels: enhancement, patch-version

#381 Fix/socket subscriptions
  api/controllers/game/ready.js
  package.json
  src/plugins/sails.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
Labels: bug, patch-version

#365 fix: set allowNull: true on non-required model attributes
  api/models/Match.js
  api/models/Season.js
  package.json
  tests/e2e/specs/in-game/gameOver.spec.js
Labels: requires migration, dev experience, patch-version

#388 Refactortests
  package.json
  tests/e2e/fixtures/userFixtures.js
  tests/e2e/specs/in-game/gameOver.spec.js
  tests/e2e/specs/in-game/reconnecting.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/authentication.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/specs/out-of-game/navigation.spec.js
  tests/e2e/specs/out-of-game/rules.spec.js
  tests/e2e/specs/out-of-game/stats.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
Labels: dev experience, patch-version
