Repository cuttle-cards/cuttle, pull requests merged in 2023-08, with the labels that each got.

#474 fix: stop requesting to leave games from the home page
  package.json
  src/views/HomeView.vue
Labels: enhancement, patch-version

#457 Add Translations via Vue i18n
  package-lock.json
  package.json
  src/components/Global/MarkdownContent.vue
  src/components/NavigationDrawer.vue
  src/i18n.js
  src/main.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/views/LoginView.vue
Labels: enhancement, help wanted

#490 Feature: Upgrade to Cypress 12
  package-lock.json
  package.json
  tests/e2e/specs/in-game/socket.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/support/commands.js
Labels: enhancement

#494 Feature: Update packages to latest versions
  package-lock.json
  package.json
  src/components/CreateGameDialog.vue
  src/components/Global/BaseSnackbar.vue
  src/components/StatsScoringDialog.vue
Labels: enhancement, dev experience

#495 Feat: Update Prettier to version 3
  package-lock.json
  package.json
Labels: enhancement, dev experience

#486 Feat: Initial docker support
  .dockerignore
  .gitignore
  config/env/staging.js
  config/sockets.js
  docker/Dockerfile
  docker/data/.gitkeep
  docker/docker-compose.yml
  docs/docker/architecture-diagram.drawio
  docs/docker/architecture-diagram.png
  docs/docker/docker.md
  docs/setup-development.md
  package-lock.json
  package.json
  src/components/Global/MarkdownContent.vue
  src/plugins/sails.js
  vite.config.js
Labels: enhancement, dev experience
