Repository cuttle-cards/cuttle, pull requests merged in 2023-12, with the labels that each got.

#826 fix: prevent NPE by replacing 'function' with () =>
  src/stores/game.js
Labels: bug, version-patch

#818 Feature: Automatic release based on version bump
  .github/workflows/bump-version.yml
  .github/workflows/prepare-version-bump.yml
  package.json
Labels: enhancement, dev experience, version-minor

#830 Feature: Automatic release based on version bump
  .github/workflows/bump-version.yml
  .github/workflows/prepare-version-bump.yml
Labels: enhancement, dev experience, version-minor

#831 Fix version parse logic
  .github/workflows/prepare-version-bump.yml
Labels: bug, version-minor

#778 Enable translating Snackbar errors in GameView
  api/controllers/game/draw.js
  api/controllers/game/face-card.js
  api/controllers/game/jack.js
  api/controllers/game/points.js
  api/controllers/game/scuttle.js
  api/controllers/game/seven/face-card.js
  api/controllers/game/seven/jack.js
  api/controllers/game/seven/points.js
  api/controllers/game/seven/scuttle.js
  api/controllers/game/seven/targeted-one-off.js
  api/controllers/game/seven/untargeted-one-off.js
  api/controllers/game/targeted-one-off.js
  src/routes/game/GameView.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/fixtures/snackbarError.js
Labels: version-minor, internationalization

#832 Wrong Variable Names in UpdateGame()
  src/stores/game.js
Labels: bug, version-patch

#736 Fix for Issue/#720.
  src/routes/lobby/components/LobbyPlayerIndicator.vue
  src/stores/game.js
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: version-patch

#843 Feat/santa logo
  public/img/logo-santa.png
  src/composables/themedLogo.js
Labels: version-minor, frontend

#844 Translate the rematch text in the GameOverDialog #789
  src/routes/game/components/GameOverDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: version-patch, frontend, internationalization

#848 Bug #847 Reauthenticate dialog username input
  src/routes/game/components/ReauthenticateDialog.vue
  tests/e2e/specs/in-game/reconnecting.spec.js
Labels: bug, version-patch, frontend

#727 feat: internationalization applied to statsView
  src/routes/game/components/ScrapDialog.vue
  src/routes/stats/StatsView.vue
  src/routes/stats/components/StatsLeaderboard.vue
  src/routes/stats/components/StatsLeaderboardCell.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: version-minor, internationalization

#846 Feat #845 Auto-generate rematch game names with score
  api/controllers/game/rematch.js
  tests/e2e/specs/in-game/gameOver.spec.js
Labels: enhancement, version-minor, backend

#835 Testing the language files
  tests/e2e/specs/out-of-game/localization.spec.js
Labels: dev experience, version-patch
