Repository cuttle-cards/cuttle, pull requests merged in 2024-05, with the labels that each got.

#904 Fix/heap memory crashes
  Procfile
  api/controllers/StatsController.js
  config/env/development.js
Labels: bug, version-patch, backend

#893 Bug#788 lobbysound
  src/routes/lobby/LobbyView.vue
  src/util/audio.js
Labels: bug, version-patch, frontend

#888 feat: Redesign Rules/About Page
  public/img/rulesView/leaderboard_example.jpg
  public/img/rulesView/oneoffs_ace.svg
  public/img/rulesView/oneoffs_eight.svg
  public/img/rulesView/oneoffs_five.svg
  public/img/rulesView/oneoffs_four.svg
  public/img/rulesView/oneoffs_nine.svg
  public/img/rulesView/oneoffs_seven.svg
  public/img/rulesView/oneoffs_six.svg
  public/img/rulesView/oneoffs_three.svg
  public/img/rulesView/oneoffs_two.svg
  public/img/rulesView/royals_jack.svg
  public/img/rulesView/royals_king.svg
  public/img/rulesView/royals_queen.svg
  public/img/rulesView/rules_action_clubs.svg
  public/img/rulesView/rules_action_diamond.svg
  public/img/rulesView/rules_action_draw.svg
  public/img/rulesView/rules_action_hearts.svg
  public/img/rulesView/rules_action_oneoffs.svg
  public/img/rulesView/rules_action_points.svg
  public/img/rulesView/rules_action_royals.svg
  public/img/rulesView/rules_action_skull.svg
  public/img/rulesView/rules_action_spades.svg
  src/App.vue
  src/components/AwardCard.vue
  src/components/BackToTop.vue
  src/router.js
  src/routes/rules/RulesView.vue
  src/routes/rules/components/RuleParagraph.vue
  src/routes/rules/components/RulePreview.vue
  src/routes/rules/components/RulePreviewDialog.vue
  src/routes/rules/components/ScuttleSuitOrder.vue
  src/routes/rules/data/rulesData.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/out-of-game/rules.spec.js
Labels: enhancement, version-minor, frontend

#909 Bug #883 conceding while resolve 7
  src/stores/game.js
  tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
Labels: bug, version-patch, frontend

#910 CSS Fixes for Rules Page
  src/App.vue
  src/routes/rules/components/ScuttleSuitOrder.vue
Labels: bug, version-patch, frontend

#912 fid(ScuttleSuitOrder): fix mobile breakpoint to be smAndDown
  src/routes/rules/components/ScuttleSuitOrder.vue
Labels: version-patch, frontend

#914 fix(LobbyView): play join sound when game starts
  src/routes/lobby/LobbyView.vue
Labels: bug, version-patch, frontend

#919 Fix RulesView responsive styles
  src/components/BackToTop.vue
  src/routes/rules/RulesView.vue
Labels: bug, version-patch, frontend

#920 Fix/rules page nav
  src/routes/rules/RulesView.vue
  src/routes/rules/data/rulesData.js
Labels: version-patch, frontend

#921 programmatically scroll the top nav when highlighting its jump link
  src/routes/rules/RulesView.vue
Labels: enhancement, version-patch, frontend

#900 DevEx #866 Utilize Sleep
  src/plugins/sockets/inGameEvents.js
  src/stores/game.js
Labels: dev experience, version-patch

#922 Bug/ overlaping of GameCardName component in dialogs(https://github.c…
  src/routes/game/components/GameCardName.vue
Labels: bug, version-patch, frontend

#924 Fix/rules view glasses gif
  src/routes/rules/RulesView.vue
  src/routes/rules/components/RulePreview.vue
  src/routes/rules/data/rulesData.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: bug, version-patch, frontend

#925 Feat/move gifs
  tests/e2e/playground/playground.config.js
  tests/e2e/playground/specs/videoPlayground.spec.js
Labels: version-minor, frontend

#927 Style/rules cleanup
  public/img/rulesView/oneoffs_ace.png
  public/img/rulesView/oneoffs_ace.svg
  public/img/rulesView/oneoffs_eight.svg
  public/img/rulesView/oneoffs_five.png
  public/img/rulesView/oneoffs_five.svg
  public/img/rulesView/oneoffs_four.png
  public/img/rulesView/oneoffs_four.svg
  public/img/rulesView/oneoffs_nine.png
  public/img/rulesView/oneoffs_nine.svg
  public/img/rulesView/oneoffs_seven.png
  public/img/rulesView/oneoffs_seven.svg
  public/img/rulesView/oneoffs_six.png
  public/img/rulesView/oneoffs_six.svg
  public/img/rulesView/oneoffs_ten.png
  public/img/rulesView/oneoffs_three.png
  public/img/rulesView/oneoffs_three.svg
  public/img/rulesView/oneoffs_two.png
  public/img/rulesView/oneoffs_two.svg
  public/img/rulesView/royals_eight.png
  public/img/rulesView/royals_jack.png
  public/img/rulesView/royals_jack.svg
  public/img/rulesView/royals_king.png
  public/img/rulesView/royals_king.svg
  public/img/rulesView/royals_queen.png
  public/img/rulesView/royals_queen.svg
  src/App.vue
  src/routes/rules/RulesView.vue
  src/routes/rules/components/FAQEntry.vue
  src/routes/rules/components/RuleParagraph.vue
  src/routes/rules/components/RulePreview.vue
  src/routes/rules/components/RulesNav.vue
  src/routes/rules/data/rulesData.js
  src/sass/typography.scss
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: enhancement, version-patch, frontend
