Repository cuttle-cards/cuttle, pull requests merged in 2024-02, with the labels that each got.

#875 fix(rematch.js): set usernames correctly in new game name
  api/controllers/game/rematch.js
Labels: bug, version-patch

#876 Feat/video playground
  docs/setup-development.md
  package.json
  tests/e2e/playground/playground.config.js
  tests/e2e/playground/specs/setupGameAsP0Flake.spec.js
  tests/e2e/playground/specs/videoPlayground.spec.js
Labels: version-patch

#865 bug/446 Close buttons have wrong style in TargetingOverlay
  src/routes/game/components/MoveChoiceOverlay.vue
  src/routes/game/components/TargetSelectionOverlay.vue
  src/routes/game/components/dialogs/components/RulesDialog.vue
  src/routes/game/components/dialogs/components/ScrapDialog.vue
Labels: bug, version-patch, frontend

#880 Increase border radius of card selection
  src/routes/game/components/GameCard.vue
Labels: version-patch, frontend
