Repository cuttle-cards/cuttle, pull requests merged in 2024-07, with the labels that each got.

#978 DevEx #974 Refactor Cypress Commands
  cypress.config.js
  src/stores/game.js
  tests/e2e/support/commands.js
Labels: version-patch, testing automation

#976 Feat/backend unit tests
  .eslintrc.js
  api/controllers/TestController.js
  api/helpers/wipe-database.js
  package.json
  tests/unit/setup.vitest.js
  tests/unit/specs/client-config.spec.js
  tests/unit/specs/sails-basics.spec.js
  tests/unit/test.spec.js
  tests/unit/util/server.util.js
  vite.config.js
Labels: version-minor, backend, testing automation

#982 Updated FiveChangeDialog
  src/routes/home/components/FiveChangeDialog.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/game-over/rematch.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/authentication.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/specs/out-of-game/localization.spec.js
  tests/e2e/specs/out-of-game/navigation.spec.js
  tests/e2e/specs/out-of-game/rules.spec.js
  tests/e2e/specs/out-of-game/stats.spec.js
Labels: version-patch, frontend

#980 Feature/940
  api/helpers/gamestate/convert-card-to-str.js
  api/helpers/gamestate/convert-str-to-card.js
  api/helpers/gamestate/pack-gamestate.js
  api/helpers/gamestate/save-gamestate.js
  api/helpers/gamestate/unpack-gamestate.js
  api/helpers/gamestate/validate-gamestate.js
  tests/unit/fixtures/Card.js
  tests/unit/fixtures/gameState.js
  tests/unit/specs/game-state.spec.js
  tests/unit/specs/sails-basics.spec.js
Labels: version-minor, backend

#985 Fix vittest document error
  tests/unit/specs/client-config.spec.js
Labels: bug, version-patch

#986 Unit test Devtools Bugfix
  tests/unit/specs/client-config.spec.js
  utils/config-utils.js
Labels: bug, version-patch, testing automation

#987 MoveType enum refactor to string
  api/helpers/gamestate/validate-gamestate.js
  api/models/GameStateRow.js
  tests/unit/fixtures/gameState.js
  utils/MoveType.json
Labels: dev experience, version-patch, backend
