Repository cuttle-cards/cuttle, pull requests merged in 2024-03, with the labels that each got.

#887 Minor spelling fixes & re-arranging of some text
  docs/setup-development.md
Labels: documentation, version-patch

#890 chore: remove stale 'global.collapseMenu' key from all translation files
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: version-patch, frontend, internationalization

#878 Bug#877 Reconnecting after game over
  api/controllers/UserController.js
  api/controllers/game/concede.js
  api/controllers/game/face-card.js
  api/controllers/game/jack.js
  api/controllers/game/pass.js
  api/controllers/game/points.js
  api/controllers/game/rematch.js
  api/controllers/game/resolve.js
  api/controllers/game/seven/face-card.js
  api/controllers/game/seven/jack.js
  api/controllers/game/seven/points.js
  api/controllers/game/stalemate.js
  src/plugins/sockets/connectivityEvents.js
  src/stores/auth.js
  tests/e2e/specs/in-game/reconnecting.spec.js
  tests/e2e/support/commands.js
Labels: bug, version-patch, backend, frontend

#895 added a conditional statement in statsUsageChart template for the issue #885
  src/routes/stats/StatsView.vue
  tests/e2e/fixtures/statsFixtures.js
Labels: enhancement, version-patch, frontend

#872 Feat #674 join lobby by URL
  api/controllers/game/spectate.js
  api/controllers/game/subscribe.js
  api/hooks/customGameHook/index.js
  src/router.js
  src/routes/home/HomeView.vue
  src/routes/home/components/GameListItem.vue
  src/routes/login/LoginView.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/fixtures/snackbarError.js
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: version-minor, frontend

#891 feat: switch from hash history to web history
  api/controllers/TestController.js
  api/controllers/ViewController.js
  config/env/development.js
  config/routes.js
  docs/CONTRIBUTING.md
  docs/GAME_RULES.md
  docs/game-rules.md
  src/router.js
  src/routes/error/NotFoundView.vue
  src/routes/home/HomeView.vue
  src/routes/stats/StatsView.vue
  src/stores/auth.js
  src/stores/game.js
  src/stores/gameList.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/game-over/rankedMatches.spec.js
  tests/e2e/specs/in-game/game-over/rematch.spec.js
  tests/e2e/specs/in-game/reconnecting.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/authentication.spec.js
  tests/e2e/specs/out-of-game/error.spec.js
  tests/e2e/specs/out-of-game/health.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/specs/out-of-game/navigation.spec.js
  tests/e2e/specs/out-of-game/other.spec.js
  tests/e2e/specs/out-of-game/rules.spec.js
  tests/e2e/specs/out-of-game/stats.spec.js
  tests/e2e/support/commands.js
  vite.config.js
Labels: enhancement, version-major, backend, frontend

#896 Bug #884 Spectate game as player
  api/controllers/game/spectate.js
  src/routes/home/components/GameListItem.vue
  src/stores/game.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/out-of-game/home.spec.js
Labels: bug, version-patch, backend, frontend

#899 Partial fix for #892 - :deep selector
  src/routes/game/GameView.vue
Labels: bug, version-patch, frontend
