Repository cuttle-cards/cuttle, pull requests merged in 2024-06, with the labels that each got.

#824 DevEx #811 Postgres migration to timestamptz
  api/controllers/StatsController.js
  api/controllers/TestController.js
  api/helpers/ find-spectatable-games.js
  api/helpers/add-game-to-match.js
  api/helpers/find-or-create-current-match.js
  api/helpers/get-seasons-without-rankings.js
  api/helpers/lock-game.js
  api/hooks/customGameHook/index.js
  api/models/Game.js
  api/models/Match.js
  api/models/Season.js
  config/models.js
  tests/e2e/fixtures/statsFixtures.js
  tests/e2e/specs/in-game/game-over/rankedMatches.spec.js
  tests/e2e/specs/in-game/game-over/rematch.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
Labels: requires migration, dev experience, version-major, backend

#931 Fix for issue 930
  src/components/AwardCard.vue
Labels: bug, version-patch, frontend

#928 Bug/897
  src/components/BackToTop.vue
  src/routes/game/components/dialogs/components/RulesDialog.vue
  src/routes/rules/RulesView.vue
  src/routes/rules/components/RulesNav.vue
Labels: version-patch, frontend

#933 Fix Issue 932
  src/routes/rules/components/RulePreviewDialog.vue
Labels: bug, version-patch, frontend

#934 Issue 779: Allow spectator to "Go Home" when game dialog is active
  src/routes/game/GameView.vue
Labels: enhancement, version-patch, frontend

#935 Feature 907: Translate the values still in English in the Spanish and French translation files
  src/translations/es.json
  src/translations/fr.json
Labels: bug, version-patch, frontend, internationalization

#936 Update game-rules.md
  docs/game-rules.md
Labels: documentation, version-patch

#971 Store API Call Refactor
  src/stores/game.js
Labels: version-patch, frontend

#970 Issue 937: Create GameState model
  api/models/Game.js
  api/models/GameStateRow.js
  utils/GamePhase.json
  utils/MoveType.json
Labels: version-minor, backend

#973 Issue 938: Create feature flag for using new API
  api/policies/gameStateAPIEnabled .js
  package.json
  src/stores/game.js
  tests/e2e/support/commands.js
Labels: dev experience, version-minor, backend, frontend
