Repository cuttle-cards/cuttle, pull requests merged in 2024-10, with the labels that each got.

#1062 fix: set playedCard and targetCard to null when appropriate
  api/helpers/gamestate/moves/draw/execute.js
  api/helpers/gamestate/moves/face-card/execute.js
  api/helpers/gamestate/moves/pass/execute.js
  api/helpers/gamestate/moves/points/execute.js
  api/helpers/gamestate/moves/seven-points/execute.js
Labels: bug, version-patch, game state api

#1054 Feat/resolve two gamestate
  api/helpers/gamestate/moves/resolve/execute.js
  api/helpers/gamestate/moves/resolve/two.js
  api/helpers/gamestate/moves/seven-points/execute.js
  tests/e2e/specs/in-game/one-offs/2_twos-destroy-target-royal.spec.js
Labels: version-minor, backend, game state api

#1064 Fix: Rename MoveType constants for issue #1027
  api/helpers/gamestate/get-log.js
  api/helpers/gamestate/moves/face-card/execute.js
  api/helpers/gamestate/moves/face-card/validate.js
  api/policies/hasValidMoveBody.js
  src/stores/game.js
  tests/e2e/support/commands.js
  utils/MoveType.json
Labels: dev experience, version-patch

#1065 Configure ESLint to enforce consistent spacing in Comments
  .eslintrc.js
  api/controllers/game/concede.js
  api/controllers/game/counter.js
  api/controllers/game/draw.js
  api/controllers/game/jack.js
  api/controllers/game/load-fixture-gamestate.js
  api/controllers/game/move.js
  api/controllers/game/resolve-five.js
  api/controllers/game/resolve.js
  api/controllers/game/seven/jack.js
  api/controllers/game/seven/scuttle.js
  api/controllers/game/seven/targeted-one-off.js
  api/controllers/game/targeted-one-off.js
  api/controllers/game/untargeted-one-off.js
  api/helpers/gamestate/convert-card-to-str.js
  api/helpers/gamestate/convert-str-to-card.js
  api/helpers/gamestate/moves/resolve/two.js
  api/helpers/gamestate/publish-game-state.js
  api/helpers/gamestate/save-gamestate.js
  api/hooks/customPasswordHook/index.js
  api/hooks/customUserHook/index.js
  api/models/Card.js
  api/models/Game.js
  api/services/cardService.js
  api/services/gameService.js
  api/services/userService.js
  config/config.js
  config/policies.js
  src/App.vue
  src/routes/game/components/MoveChoiceOverlay.vue
  src/stores/game.js
  tests/e2e/specs/in-game/game-over/winConditions.spec.js
  tests/e2e/specs/in-game/one-offs/0_countering.spec.js
  tests/e2e/specs/in-game/one-offs/3_threes.spec.js
  tests/e2e/specs/in-game/one-offs/5_fives.spec.js
  tests/e2e/specs/in-game/one-offs/6_sixes.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/opponent_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/9_nines.spec.js
  tests/e2e/specs/in-game/one-offs/targeting_cleanup.spec.js
  tests/e2e/specs/in-game/reconnecting.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/specs/out-of-game/stats.spec.js
  tests/e2e/support/commands.js
  tests/unit/specs/game-state.spec.js
Labels: dev experience, version-patch

#1075 Fix/resolve increment turn on fizzle
  api/helpers/game-states/moves/resolve/execute.js
  tests/e2e/specs/in-game/one-offs/0_countering.spec.js
Labels: bug, version-patch, testing automation, game state api

#1069 resolve six in gamestate api
  api/helpers/game-states/moves/resolve/execute.js
  api/helpers/game-states/moves/resolve/six.js
  tests/e2e/specs/in-game/one-offs/6_sixes.spec.js
Labels: version-minor, backend

#1060 Feature #1022 reveal opponent hand on exhausted deck
  public/img/announcement/deck-exhausted.gif
  src/routes/game/GameView.vue
  src/routes/home/components/announcementDialog/AnnouncementDialog.vue
  src/routes/home/components/announcementDialog/data/announcementData.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/basicMoves.spec.js
  tests/e2e/specs/in-game/one-offs/3_threes.spec.js
  tests/e2e/specs/in-game/one-offs/4_fours.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/end_of_deck_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/opponent_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/9_nines.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/authentication.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/specs/out-of-game/lobby.spec.js
  tests/e2e/support/helpers.js
Labels: enhancement, version-minor, frontend

#1078 Fix/announcement header length
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: bug, version-patch, frontend, internationalization

#1081 Fix/empty deck snackbar conditional
  src/routes/game/GameView.vue
  tests/e2e/specs/in-game/game-over/rematch.spec.js
Labels: bug, version-patch, frontend

#1059 feat: adds Resolving Three move support in GameState API
  api/helpers/game-states/moves/resolve-three/execute.js
  api/helpers/game-states/moves/resolve-three/validate.js
  api/policies/hasValidMoveBody.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/one-offs/3_threes.spec.js
Labels: version-minor, backend

#1079 Feat #1036 enter lobby after room creation
  src/routes/home/components/CreateGameDialog.vue
  tests/e2e/specs/out-of-game/home.spec.js
Labels: enhancement, hacktoberfest, version-minor, frontend

#1088 Update redis-connect
  config/env/production.js
  package-lock.json
  package.json
Labels: bug, version-minor

#1077 Update (almost) all of the dependencies
  .github/workflows/run-npm-script.yml
  .husky/pre-push
  .nvmrc
  api/controllers/HealthController.js
  config/routes.js
  docker/Dockerfile
  package-lock.json
  package.json
  tests/unit/specs/client-config.spec.js
  tools/msg-bump-version.js
  utils/config-utils.js
  vite.config.mjs
Labels: dev experience, version-minor

#1092 Fix/GameView jacks container adjustment (#1029)
  src/routes/game/GameView.vue
  src/routes/game/components/GameCard.vue
Labels: bug, hacktoberfest, version-patch, frontend

#1072 feat: implements resolve four in GameState API
  api/helpers/game-states/moves/resolve-four/execute.js
  api/helpers/game-states/moves/resolve-four/validate.js
  api/policies/hasValidMoveBody.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/game-over/winConditions.spec.js
  tests/e2e/specs/in-game/one-offs/4_fours.spec.js
Labels: hacktoberfest, version-minor, backend

#1093 Refactor/points validate assignment
  api/helpers/game-states/moves/points/validate.js
Labels: enhancement, hacktoberfest, version-patch, backend, game state api

#1095 Feat #945 Add refresh to game menu
  src/routes/game/components/GameMenu.vue
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/reconnecting.spec.js
Labels: enhancement, hacktoberfest, version-minor, frontend

#1105 Configured ESLint to require newline at end of files
  .eslintrc.js
  src/components/BaseLineChart.vue
  src/routes/game/components/dialogs/components/ScrapDialog.vue
Labels: hacktoberfest, dev experience, version-patch

#1102 [Bug]: Replace public/img/logo-dead.svg #1099
  public/img/logo-dead.svg
Labels: bug, hacktoberfest, version-patch, frontend

#1073 replaced game with gameStore
  src/routes/game/GameView.vue
Labels: hacktoberfest, dev experience, version-patch, frontend

#1106 test(player_sevens.spec): add test to validate illegal scuttles
  api/helpers/game-states/moves/seven-points/validate.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
Labels: hacktoberfest, dev experience, version-patch, testing automation, game state api

#1098 feature_seven_scuttle
  api/helpers/game-states/moves/seven-points/validate.js
  api/helpers/game-states/moves/seven-scuttle/execute.js
  api/helpers/game-states/moves/seven-scuttle/validate.js
  api/policies/hasValidMoveBody.js
  tests/e2e/specs/in-game/one-offs/7_sevens/opponent_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
Labels: hacktoberfest, version-minor, backend

#1104 Implement resolve-five functionality
  api/helpers/game-states/moves/resolve-five/execute.js
  api/helpers/game-states/moves/resolve-five/validate.js
  api/policies/hasValidMoveBody.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  tests/e2e/specs/in-game/one-offs/5_fives.spec.js
  tests/e2e/specs/in-game/one-offs/targeting_cleanup.spec.js
Labels: hacktoberfest, version-minor, backend
