Repository cuttle-cards/cuttle, pull requests merged in 2024-01, with the labels that each got.

#849 Bug/503
  api/controllers/game/spectate.js
Labels: bug, dev experience, version-patch, backend

#840 titles must be capitalized
  docs/translation-guidelines.md
Labels: documentation, version-patch

#854 Bug: 853 Stalemate bug
  api/controllers/game/stalemate.js
  src/stores/game.js
  tests/e2e/specs/in-game/gameOver.spec.js
Labels: bug, version-patch, backend, frontend

#834 Optimized the bg-image file
  public/img/game/board-background.svg
  public/img/game/board-background.webp
  src/routes/game/GameView.vue
  src/routes/login/LoginView.vue
  src/routes/rematch/RematchView.vue
Labels: version-patch, frontend

#858 [Feature]: Add reverse water effect in the lobby cards #792
  src/routes/lobby/LobbyView.vue
  src/routes/lobby/components/LobbyPlayerIndicator.vue
Labels: version-patch, frontend

#863 Bug #861 Card names undefined
  api/controllers/game/seven/jack.js
Labels: bug, version-patch

#873 Bug #870 Redundant stats link error
  src/routes/stats/StatsView.vue
Labels: bug, version-patch, frontend

#852 Feat/rematch redesign
  api/controllers/game/concede.js
  api/controllers/game/join-rematch.js
  api/controllers/game/pass.js
  api/controllers/game/rematch.js
  api/controllers/game/stalemate.js
  api/helpers/add-game-to-match.js
  api/helpers/get-casual-match.js
  api/helpers/get-rematch-games.js
  api/services/gameService.js
  public/img/cards/card-back-declined.png
  public/img/cards/card-rematch.png
  public/img/logo-trophy.svg
  src/components/PlayerReadyIndicator.vue
  src/plugins/sockets/inGameEvents.js
  src/router.js
  src/routes/game/GameView.vue
  src/routes/game/components/GameMenu.vue
  src/routes/game/components/GameOverDialog.vue
  src/routes/game/components/GameUnavailableView.vue
  src/routes/game/components/dialogs/GameDialogs.vue
  src/routes/game/components/dialogs/components/CannotCounterDialog.vue
  src/routes/game/components/dialogs/components/ChooseTwoDialog.vue
  src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue
  src/routes/game/components/dialogs/components/CounterDialog.vue
  src/routes/game/components/dialogs/components/FourDialog.vue
  src/routes/game/components/dialogs/components/OpponentRequestedStalemateDialog.vue
  src/routes/game/components/dialogs/components/ReauthenticateDialog.vue
  src/routes/game/components/dialogs/components/RulesDialog.vue
  src/routes/game/components/dialogs/components/ScrapDialog.vue
  src/routes/game/components/dialogs/components/SevenDoubleJacksDialog.vue
  src/routes/game/components/dialogs/components/ThreeDialog.vue
  src/routes/game/components/dialogs/components/gameOver/GameOverDialog.vue
  src/routes/game/components/dialogs/components/gameOver/components/MatchScoreCounter.vue
  src/routes/game/components/dialogs/components/gameOver/components/MatchStatusBanner.vue
  src/routes/game/components/dialogs/components/gameOver/components/MatchWonOrLostIndicator.vue
  src/routes/game/components/dialogs/components/gameOver/composables/playerData.js
  src/routes/lobby/LobbyView.vue
  src/routes/rematch/RematchView.vue
  src/stores/game.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/util/sleep.js
  tests/e2e/specs/in-game/game-over/rankedMatches.spec.js
  tests/e2e/specs/in-game/game-over/rematch.spec.js
  tests/e2e/specs/in-game/game-over/winConditions.spec.js
  tests/e2e/specs/in-game/gameOver.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
  types/SocketEvent.js
Labels: version-major, backend, frontend
