Repository cuttle-cards/cuttle, pull requests merged in 2024-12, with the labels that each got.

#1116 Feat/concede
  api/helpers/add-game-to-match.js
  api/helpers/game-states/check-game-state-for-win.js
  api/helpers/game-states/moves/concede/execute.js
  api/helpers/game-states/moves/concede/validate.js
  api/policies/hasValidMoveBody.js
  src/stores/game.js
  tests/e2e/specs/in-game/reconnecting.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/support/commands.js
  types/SocketEvent.js
  utils/MoveType.json
Labels: version-minor, backend

#1134 Fix/navigate home from spectate
  src/routes/game/components/GameUnavailableOverlay.vue
  src/routes/game/components/dialogs/components/gameOver/GameOverDialog.vue
Labels: bug, version-patch, frontend

#1133 test: remove .only()'s
  tests/e2e/playground/specs/setupGameAsP0Flake.spec.js
  tests/e2e/specs/in-game/one-offs/9_nines.spec.js
Labels: dev experience, version-patch, testing automation

#1136 Feature #1132 Navbar logo link to home
  src/components/TheHeader.vue
  tests/e2e/specs/out-of-game/navigation.spec.js
Labels: version-patch, frontend

#1138 feat(.github): bump download-artifact and upload-artifact to v4
  .github/workflows/prepare-version-bump.yml
  .github/workflows/test-e2e.yml
Labels: dev experience, version-patch

#1139 fix(en.json): fix typo in announcement.paragraph
  src/translations/en.json
Labels: version-patch, frontend, internationalization
