Repository cuttle-cards/cuttle, pull requests merged in 2024-08, with the labels that each got.

#989 Bug #871 /Game and /Spectate bring you to blank screen
  src/router.js
Labels: bug, version-patch, frontend

#981 Feature #943 create emit game state
  api/helpers/gamestate/check-game-state-for-win.js
  api/helpers/gamestate/convert-card-to-str.js
  api/helpers/gamestate/get-log.js
  api/helpers/gamestate/pack-gamestate.js
  api/helpers/gamestate/publish-game-state.js
  api/helpers/gamestate/unpack-gamestate.js
  api/helpers/gamestate/validate-gamestate.js
  api/models/GameStateRow.js
  src/routes/game/GameView.vue
  src/routes/game/components/MoveChoiceOverlay.vue
  tests/unit/fixtures/Game.js
  tests/unit/fixtures/gameState.js
  tests/unit/fixtures/gameStates/points.js
  tests/unit/fixtures/gameStates/resolveNine.js
  tests/unit/fixtures/gameStates/resolveThree.js
  tests/unit/specs/game-state.spec.js
Labels: version-minor, backend, frontend

#995 deleted GAME-RULES.md
  docs/GAME_RULES.md
Labels: version-patch

#999 added an FAQ entry in the json file
  src/routes/rules/data/rulesData.js
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: enhancement, version-patch, frontend

#1007 vue warning about `parentModalId` type
  src/routes/rules/RulesView.vue
Labels: bug, dev experience, version-patch, frontend

#1011 Bug#1010 GH Actions Gamestate Fix
  .github/workflows/test-e2e-gamestate.yml
Labels: version-patch, testing automation

#984 Feat/deal cards gamestate
  api/controllers/game/get-list.js
  api/controllers/game/leave-lobby.js
  api/controllers/game/ready.js
  api/controllers/game/rematch.js
  api/controllers/game/subscribe.js
  api/helpers/gamestate/deal-cards.js
  api/helpers/gamestate/validate-gamestate.js
  api/helpers/get-rematch-games.js
  api/helpers/lock-game.js
  api/services/gameService.js
  src/plugins/sockets/inGameEvents.js
  tests/unit/fixtures/gameStates/points.js
  types/SocketEvent.js
  utils/DeckIds.json
  utils/MoveType.json
Labels: version-minor, backend
