Repository cuttle-cards/cuttle, pull requests merged in 2024-11, with the labels that each got.

#1091 Add .gitattributes to handle line endings between operating systems
  .gitattributes
  public/img/logo-head.svg
  public/img/logo.svg
Labels: hacktoberfest, hacktoberfest-accepted, dev experience, version-patch

#1109 Add icons to the UserMenu activator
  src/components/TheUserMenu.vue
Labels: version-patch, frontend

#1085 Feature #1034 Validate All Cards
  .github/workflows/run-npm-script.yml
  .nvmrc
  api/controllers/game/load-fixture-gamestate.js
  api/controllers/game/load-fixture.js
  api/helpers/game-states/moves/resolve/execute.js
  api/helpers/game-states/validate-all-cards.js
  api/helpers/game-states/validate-gamestate.js
  package.json
  tests/e2e/specs/in-game/game-over/rematch.spec.js
  tests/e2e/specs/in-game/one-offs/5_fives.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/end_of_deck_sevens.spec.js
  tests/e2e/specs/in-game/one-offs/7_sevens/player_sevens.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
  tests/unit/fixtures/gameStates/cardValidationErrors.js
  tests/unit/fixtures/gameStates/points.js
  tests/unit/fixtures/gameStates/resolveNine.js
  tests/unit/fixtures/gameStates/resolveThree.js
  tests/unit/specs/sails/game-state.spec.js
Labels: hacktoberfest, hacktoberfest-accepted, version-minor, backend

#1119 Add Rollbar Vue error tracking, resolves #368
  .env
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  src/plugins/rollbar.js
Labels: enhancement, dev experience, version-minor, frontend

#1120 Feat #969 Resolve Nine Gamestate
  api/controllers/game/seven/jack.js
  api/helpers/game-states/moves/resolve/execute.js
  api/helpers/game-states/moves/resolve/nine.js
  api/helpers/game-states/moves/resolve/two.js
  src/routes/game/components/MoveChoiceOverlay.vue
  src/stores/game.js
  tests/e2e/playground/specs/videoPlayground.spec.js
  tests/e2e/specs/in-game/one-offs/9_nines.spec.js
  utils/TargetType.json
Labels: version-minor, backend
