Repository cuttle-cards/cuttle, pull requests merged in 2025-01, with the labels that each got.

#1135 Feat/spectate gamestate
  api/controllers/game/spectate-leave.js
  api/controllers/game/spectate/join.js
  api/controllers/game/spectate/leave.js
  api/helpers/game-states/create-socket-event.js
  api/policies/isInGame.js
  config/routes.js
  src/plugins/sockets/inGameEvents.js
  src/routes/home/components/GameListItem.vue
  src/stores/game.js
  tests/e2e/fixtures/snackbarError.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/support/commands.js
Labels: version-minor, backend

#1143 feat(helpers/moves): set playedBy, playedCard, targetCard, discardedC…
  api/helpers/game-states/moves/counter/execute.js
  api/helpers/game-states/moves/draw/execute.js
  api/helpers/game-states/moves/face-card/execute.js
  api/helpers/game-states/moves/jack/execute.js
  api/helpers/game-states/moves/one-off/execute.js
  api/helpers/game-states/moves/pass/execute.js
  api/helpers/game-states/moves/points/execute.js
  api/helpers/game-states/moves/resolve-three/execute.js
  api/helpers/game-states/moves/resolve/execute.js
  api/helpers/game-states/moves/resolve/nine.js
  api/helpers/game-states/moves/scuttle/execute.js
  api/helpers/game-states/moves/seven-discard/execute.js
  api/helpers/game-states/moves/seven-face-card/execute.js
  api/helpers/game-states/moves/seven-jack/execute.js
  api/helpers/game-states/moves/seven-one-off/execute.js
  api/helpers/game-states/moves/seven-points/execute.js
  api/helpers/game-states/moves/seven-scuttle/execute.js
Labels: version-patch, backend

#1145 Feat 929 add robot.txt file
  package-lock.json
  package.json
  public/robots.txt
  src/main.js
  src/routes/login/LoginView.vue
  tests/e2e/specs/out-of-game/authentication.spec.js
Labels: version-patch

#1147 Dev ex 1131 configure eslint to error on .only()
  .eslintrc.js
  package-lock.json
  package.json
Labels: dev experience, version-patch

#1148 1142 rework unauth status codes
  api/policies/isLoggedIn.js
  src/stores/game.js
Labels: dev experience, version-patch, backend

#1149 Dev ex 202 self host google fonts
  index.html
  public/fonts/changa/OFL.txt
  public/fonts/changa/changa-v27-arabic_latin_latin-ext-500.woff2
  public/fonts/changa/changa-v27-arabic_latin_latin-ext-700.woff2
  public/fonts/changa/changa-v27-arabic_latin_latin-ext-regular.woff2
  public/fonts/cormorantInfant/OFL.txt
  public/fonts/cormorantInfant/cormorant-infant-v17-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-600.woff2
  public/fonts/cormorantInfant/cormorant-infant-v17-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-700.woff2
  public/fonts/cormorantInfant/cormorant-infant-v17-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-regular.woff2
  public/fonts/libreBaskerville/OFL.txt
  public/fonts/libreBaskerville/libre-baskerville-v14-latin_latin-ext-700.woff2
  public/fonts/libreBaskerville/libre-baskerville-v14-latin_latin-ext-regular.woff2
  public/fonts/luckiestGuy/LICENSE.txt
  public/fonts/luckiestGuy/luckiest-guy-v23-latin_latin-ext-regular.woff2
  public/fonts/ptSerif/OFL.txt
  public/fonts/ptSerif/pt-serif-v18-cyrillic_cyrillic-ext_latin_latin-ext-700.woff2
  public/fonts/ptSerif/pt-serif-v18-cyrillic_cyrillic-ext_latin_latin-ext-regular.woff2
  public/fonts/roboto/LICENSE.txt
  public/fonts/roboto/roboto-v32-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-100.woff2
  public/fonts/roboto/roboto-v32-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-300.woff2
  public/fonts/roboto/roboto-v32-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-500.woff2
  public/fonts/roboto/roboto-v32-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-700.woff2
  public/fonts/roboto/roboto-v32-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-900.woff2
  public/fonts/roboto/roboto-v32-cyrillic_cyrillic-ext_greek_greek-ext_latin_latin-ext_vietnamese-regular.woff2
  src/App.vue
  src/sass/typography.scss
Labels: version-patch, frontend

#1151 Added German to selectable languages (#1150)
  src/i18n.js
  src/translations/de.json
  tests/e2e/specs/out-of-game/localization.spec.js
Labels: version-minor, frontend, internationalization

#1155 Feature/highlight selected lang in the dropdown and set it to top
  src/components/TheLanguageSelector.vue
Labels: version-patch, frontend, internationalization

#1110 Spades 2024 announcement
  public/img/announcement/spades-2024-bracket.svg
  src/components/BaseParagraph.vue
  src/main.js
  src/routes/home/components/announcementDialog/AnnouncementDialog.vue
  src/routes/home/components/announcementDialog/data/announcementData.js
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
Labels: enhancement, version-minor, frontend

#1160 test(home.spec): skip it('Shows the Announcement Dialog when user nav…
  tests/e2e/specs/out-of-game/home.spec.js
Labels: dev experience, version-patch, testing automation

#1158 Bug #1117 Resolve Five Animation
  src/stores/game.js
  tests/e2e/specs/in-game/one-offs/5_fives.spec.js
Labels: bug, version-patch, frontend, testing automation

#1162 Add Ukrainian as selectable language
  api/helpers/game-states/moves/jack/execute.js
  api/helpers/game-states/moves/scuttle/execute.js
  api/helpers/game-states/moves/seven-jack/execute.js
  src/i18n.js
  src/routes/game/components/dialogs/components/FourDialog.vue
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/uk.json
  tests/e2e/specs/out-of-game/localization.spec.js
Labels: version-minor, frontend, internationalization

#1161 Fix/rollbar crash
  api/controllers/TestController.js
  config/routes.js
  src/main.js
  src/plugins/rollbar.js
  src/stores/game.js
  tests/e2e/specs/in-game/spectating.spec.js
Labels: bug, version-patch, frontend
