Repository cuttle-cards/cuttle, pull requests merged in 2025-04, with the labels that each got.

#1183 Feat/clubs 2025 announcement
  public/img/announcement/clubs_2025_cuttle_season_championship.svg
  src/routes/home/components/announcementDialog/data/announcementData.js
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/ukr.json
Labels: version-patch, frontend

#1184 Feat/clubs 2025 announcement 2
  src/routes/home/components/announcementDialog/data/announcementData.js
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/ukr.json
Labels: version-patch, frontend

#1185 Fix: End date of announcement
  src/routes/home/components/announcementDialog/data/announcementData.js
Labels: bug, version-patch, frontend

#1186 Fix: Start Date for Announcement Dialog
  src/routes/home/components/announcementDialog/data/announcementData.js
Labels: bug, version-patch, frontend

#1188 feat(jsonconfig.json): init file
  jsconfig.json
Labels: dev experience, version-patch

#1187 Test/unskip gamestate tests
  api/controllers/TestController.js
  api/controllers/UserController.js
  api/controllers/game/stalemate.js
  api/helpers/add-game-to-match.js
  api/policies/deleteSession.js
  config/policies.js
  src/plugins/sockets/inGameEvents.js
  tests/e2e/specs/in-game/game-over/rematch.spec.js
  tests/e2e/specs/in-game/spectating.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
  types/SocketEvent.js
Labels: version-minor, testing automation
