Repository cuttle-cards/cuttle, pull requests merged in 2025-03, with the labels that each got.

#1169 Add profanity filter to game names and usernames
  api/policies/hasNoProfanity.js
  config/policies.js
  src/util/badWordsEn.js
  tests/e2e/specs/out-of-game/authentication.spec.js
  tests/e2e/specs/out-of-game/home.spec.js
Labels: version-patch, backend

#1171 fix/change-ranked/casual-setting-on-games-via-keyboard
  src/routes/lobby/LobbyView.vue
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: version-patch, frontend

#1172 Feat/worlds announcement
  public/img/announcement/cuttle-world-championship-iv-bracket.svg
  src/routes/home/components/announcementDialog/data/announcementData.js
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/uk.json
Labels: version-patch, frontend

#1173 feature/rename-ukrainain-language-file-to-ukr✅
  src/i18n.js
  src/translations/ukr.json
  tests/e2e/specs/out-of-game/localization.spec.js
Labels: version-patch, frontend, internationalization

#1175 Feature Dedupe and Remove 'butt' from `badWordsEn.json`
  src/util/badWordsEn.js
Labels: enhancement, version-patch

#1176 [DevEx]: Move i18n.js into `src/plugins`
  src/main.js
  src/plugins/i18n.js
Labels: version-patch, frontend
