Repository cuttle-cards/cuttle, pull requests merged in 2025-06, with the labels that each got.

#1071 Cleanup isFrozen
  api/models/User.js
  src/routes/game/GameView.vue
Labels: dev experience, version-patch, frontend

#1201 fix(scuttle/execute): scrap all jacks when scuttling
  api/helpers/game-states/moves/scuttle/execute.js
  tests/e2e/specs/in-game/basicMoves.spec.js
Labels: bug, version-patch, backend

#1204 Fix/resolve five log
  api/helpers/game-states/get-log.js
  src/routes/game/GameView.vue
  tests/e2e/specs/in-game/one-offs/5_fives.spec.js
Labels: bug, version-patch, backend

#1202 fix(LobbyView.vue): navigate to game if readying after game already started
  api/controllers/game/ready.js
  api/errors/conflictError.js
  api/errors/customErrorType.js
  src/routes/lobby/LobbyView.vue
  src/stores/game.js
  tests/e2e/specs/out-of-game/lobby.spec.js
Labels: bug, version-patch, backend, frontend

#1205 fix: disable rollbar in the hopes that this prevents the home page crashes
  src/main.js
Labels: bug, version-patch, frontend

#1208 Fix/three and maybe five logs
  api/helpers/game-states/get-log.js
  tests/e2e/specs/in-game/one-offs/3_threes.spec.js
  tests/e2e/specs/in-game/one-offs/4_fours.spec.js
  tests/e2e/specs/in-game/one-offs/5_fives.spec.js
  tests/unit/fixtures/gameStates/resolveNine.js
Labels: bug, version-patch, backend

#1211 Fix for issue #1199-color of the ranked and casual switch changed to newPrimary
  src/routes/lobby/LobbyView.vue
Labels: version-patch, frontend

#1216 Fix/replays on ranked games
  api/helpers/add-game-to-match.js
  tests/e2e/specs/in-game/game-over/rankedMatches.spec.js
  tests/e2e/specs/in-game/spectating/replays.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/helpers.js
Labels: bug, version-patch, backend

#1217 Fix/request spectate after nine
  api/helpers/game-states/moves/stalemate-reject/execute.js
  api/helpers/game-states/moves/stalemate-request/execute.js
  api/helpers/game-states/unpack-gamestate.js
  tests/e2e/specs/in-game/one-offs/9_nines.spec.js
Labels: bug, version-patch, backend

#1218 feat: enable copying clip urls
  src/routes/game/components/GameMenu.vue
  src/stores/gameHistory.js
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fr.json
  src/translations/ukr.json
  tests/e2e/specs/in-game/spectating/replays.spec.js
Labels: enhancement, version-minor, frontend

#1100 Added the original comments and also did some modifications
  src/router.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, version-minor

#1231 feat(GameMenu.vue): add icons for concede and request stalemate
  src/routes/game/components/GameMenu.vue
Labels: enhancement, version-patch, frontend

#1235 fix(game.js): fix processScuttle()'s handling of cards not being found to check for indices === -1 instaed of undefined
  src/stores/game.js
  tests/e2e/specs/in-game/spectating/replays.spec.js
  tests/e2e/support/commands.js
Labels: bug, version-patch, backend
